const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => [...document.querySelectorAll(sel)];
const state = { caseId: null, runId: null, run: null, case: null, polling: null, pendingFiles: [] };
const platformNames = { xiaohongshu:'小红书', weibo:'微博', douyin:'抖音', bilibili:'B站', other:'其他平台' };
const kindNames = { image:'图片', video:'视频', audio:'音频', document:'文档', other:'素材' };

async function api(path, options={}) {
  const headers = { ...(options.headers || {}) };
  if (!(options.body instanceof FormData)) headers['Content-Type'] = 'application/json';
  const res = await fetch(path, { ...options, headers });
  const type = res.headers.get('content-type') || '';
  const data = type.includes('application/json') ? await res.json().catch(()=>({})) : await res.text();
  if (!res.ok) throw new Error((data && data.detail) || data || '请求失败');
  return data;
}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2200)}
function pct(value){return `${Math.round((Number(value)||0)*100)}%`}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function formatTime(iso){try{const d=new Date(iso);return `${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}catch{return ''}}
function formatSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`}

async function loadCases(){try{const cases=await api('/api/cases');const list=$('#caseList');if(!cases.length){list.innerHTML='<div class="case-empty"><strong>还没有调查</strong><p>从一个账号、一组内容或几份素材开始。</p></div>';return}list.innerHTML=cases.map(item=>{const p=platformNames[item.targets?.[0]?.platform]||'调查';return `<button class="case-item ${item.id===state.caseId?'active':''}" data-id="${item.id}"><span><strong>${escapeHtml(item.title)}</strong><small>${p} · ${formatTime(item.updated_at)}</small></span></button>`}).join('');$$('.case-item').forEach(btn=>btn.addEventListener('click',()=>openCase(btn.dataset.id)))}catch(err){toast(err.message)}}

async function openCase(id){try{const item=await api(`/api/cases/${id}`);state.caseId=id;state.case=item;$('#welcome').hidden=true;$('#caseTitle').textContent=item.title;const target=item.targets?.[0]||{};$('#casePlatform').textContent=`${platformNames[target.platform]||'跨平台'} · ${target.display_name||target.handle||'账号调查'}`;$('#caseMeta').textContent=item.goal;renderMessages(item.messages||[]);renderAssets(item.assets||[]);const latest=(item.runs||[])[0];const finished=latest?.status==='completed'&&latest?.state?.primary_result?.label;$('#workspaceActions').hidden=!finished;if(latest){state.runId=latest.id;renderRun(latest);if(latest.status==='running')beginPolling(latest.id)}else clearInsight();loadCases()}catch(err){toast(err.message)}}

function renderMessages(messages){$('#messageList').innerHTML=messages.map(m=>`<article class="message ${m.role}"><span class="role">${m.role==='user'?'你':'观潮'}</span><div class="bubble">${escapeHtml(m.content).replace(/\n/g,'<br>')}</div></article>`).join('');$('#conversation').scrollTop=$('#conversation').scrollHeight}
function renderRun(run){state.run=run;const s=run.state||{};const events=s.events||[];$('#runStrip').hidden=run.status!=='running';if(run.status==='running'){const last=events[events.length-1]||{};$('#runDetail').textContent=last.detail||last.title||'正在选择下一步'}renderTrace(events);renderEvidence(s.evidence||[]);if(s.primary_result?.label||run.status==='completed')renderSummary(s.primary_result||{})}
function renderSummary(result){if(!result||!Object.keys(result).length)return;$('#summaryEmpty').hidden=true;$('#summaryContent').hidden=false;$('#verdictLabel').textContent=result.label||'待补资料';$('#confidenceValue').textContent=pct(result.confidence);$('#confidenceMeter').style.width=pct(result.confidence);$('#stabilityValue').textContent=pct(result.stability);$('#stabilityMeter').style.width=pct(result.stability);$('#marketingValue').textContent=pct(result.marketing_likelihood);$('#covertValue').textContent=pct(result.covert_promotion_risk);$('#summaryCopy').textContent=result.summary||'正在整理判断。';const missing=result.missing||[];$('#missingBlock').hidden=!missing.length;$('#missingList').innerHTML=missing.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}
function renderEvidence(evidence){const seen=new Map();evidence.forEach(item=>{const key=`${item.key}:${item.direction}`;const old=seen.get(key);if(!old||(item.strength||0)>(old.strength||0))seen.set(key,item)});const items=[...seen.values()].sort((a,b)=>(b.strength||0)-(a.strength||0));$('#evidenceList').innerHTML=items.length?items.map(item=>`<article class="evidence-item ${item.direction||'context'}"><div class="evidence-top"><strong>${escapeHtml(item.title)}</strong><em>${item.direction==='against'?'反向线索':item.direction==='supports'?'支持判断':'背景'}</em></div><p>${escapeHtml(item.detail)}</p></article>`).join(''):'<div class="side-empty">还没有足够明确的关键证据。</div>'}
function renderAssets(assets){$('#assetList').innerHTML=assets.length?assets.map(a=>`<article class="asset-item"><div class="asset-top"><strong>${escapeHtml(a.name)}</strong><span class="asset-state ${a.status}">${a.status==='ready'?'已读取':a.status==='error'?'读取失败':'待读取'}</span></div><p>${kindNames[a.kind]||'素材'} · ${formatSize(a.size||0)}${a.note?` · ${escapeHtml(a.note)}`:''}</p></article>`).join(''):'<div class="side-empty">还没有添加素材。</div>';renderUploadTray(assets)}
function renderTrace(events){$('#traceList').innerHTML=events.length?events.map(e=>`<article class="trace-item ${e.status||'done'}"><div><strong>${escapeHtml(e.title)}</strong><p>${escapeHtml(e.detail||'')}</p></div></article>`).join(''):'<div class="side-empty">每一步核查都会留在这里。</div>'}
function clearInsight(){$('#summaryEmpty').hidden=false;$('#summaryContent').hidden=true;$('#evidenceList').innerHTML='<div class="side-empty">关键证据会按支持、反向和背景分别保留。</div>';$('#traceList').innerHTML='<div class="side-empty">每一步核查都会留在这里。</div>'}
function renderUploadTray(assets){const tray=$('#uploadTray');tray.hidden=!assets.length;tray.innerHTML=assets.slice(-6).map(a=>`<span class="upload-chip"><b>${kindNames[a.kind]||'素材'}</b>${escapeHtml(a.name)}</span>`).join('')}

async function sendMessage(){const input=$('#messageInput');const content=input.value.trim();if(!content)return;if(!state.caseId){openModal();return}input.value='';autosize(input);try{const out=await api(`/api/cases/${state.caseId}/messages`,{method:'POST',body:JSON.stringify({content})});state.runId=out.run_id;const item=await api(`/api/cases/${state.caseId}`);state.case=item;renderMessages(item.messages||[]);$('#workspaceActions').hidden=true;beginPolling(out.run_id)}catch(err){toast(err.message)}}
function beginPolling(runId){clearInterval(state.polling);const tick=async()=>{try{const run=await api(`/api/runs/${runId}`);renderRun(run);if(run.status!=='running'){clearInterval(state.polling);state.polling=null;const item=await api(`/api/cases/${state.caseId}`);state.case=item;renderMessages(item.messages||[]);renderAssets(item.assets||[]);$('#workspaceActions').hidden=!(run.status==='completed'&&run.state?.primary_result?.label);loadCases()}}catch(err){clearInterval(state.polling);state.polling=null;toast(err.message)}};tick();state.polling=setInterval(tick,500)}
async function loadDemo(){try{const out=await api('/api/demo',{method:'POST'});state.caseId=out.case.id;state.runId=out.run_id;await openCase(out.case.id);beginPolling(out.run_id);toast('示例调查已开始')}catch(err){toast(err.message)}}

function openModal(){state.pendingFiles=[];renderSelectedFiles();$('#caseModal').hidden=false;$('#handleInput').focus()}
function closeModal(){$('#caseModal').hidden=true;state.pendingFiles=[];renderSelectedFiles()}
function addPendingFiles(files){state.pendingFiles=[...state.pendingFiles,...[...files]].slice(0,12);renderSelectedFiles()}
function renderSelectedFiles(){const el=$('#selectedFiles');el.hidden=!state.pendingFiles.length;el.innerHTML=state.pendingFiles.map(f=>`<span>${escapeHtml(f.name)} · ${formatSize(f.size)}</span>`).join('')}
async function uploadFiles(caseId,files){for(const file of files){const form=new FormData();form.append('file',file);await api(`/api/cases/${caseId}/assets`,{method:'POST',body:form})}}
async function uploadToCurrent(files){if(!files.length)return;if(!state.caseId){state.pendingFiles=[...files];openModal();state.pendingFiles=[...files];renderSelectedFiles();return}try{toast(`正在加入 ${files.length} 份素材`);await uploadFiles(state.caseId,files);const item=await api(`/api/cases/${state.caseId}`);state.case=item;renderAssets(item.assets||[]);toast('素材已加入当前调查')}catch(err){toast(err.message)}}
async function createCase(ev){ev.preventDefault();const posts=$('#postsInput').value.split(/\n+/).map(x=>x.trim()).filter(Boolean).map((text,i)=>({id:`p${i+1}`,text}));if(!posts.length&&!state.pendingFiles.length){toast('请至少添加一条内容或一份素材');return}const target={platform:$('#platformInput').value,handle:$('#handleInput').value.trim(),display_name:$('#handleInput').value.trim(),bio:$('#bioInput').value.trim(),posts};const goal=$('#goalInput').value.trim();const files=[...state.pendingFiles];try{const item=await api('/api/cases',{method:'POST',body:JSON.stringify({title:`${target.display_name} · 内容调查`,goal,targets:[target]})});if(files.length)await uploadFiles(item.id,files);closeModal();state.caseId=item.id;await openCase(item.id);$('#messageInput').value=goal;await sendMessage();$('#caseForm').reset()}catch(err){toast(err.message)}}
async function submitFeedback(label){if(!state.caseId)return;try{await api('/api/feedback',{method:'POST',body:JSON.stringify({case_id:state.caseId,label,note:''})});toast(label?'已记录：营销运营':'已记录：普通创作者')}catch(err){toast(err.message)}}
function switchTab(tab){$$('.insight-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.tab-panel').forEach(p=>p.classList.remove('active'));$(`#tab-${tab}`).classList.add('active')}
function autosize(el){el.style.height='auto';el.style.height=`${Math.min(150,el.scrollHeight)}px`}

$('#sendBtn').addEventListener('click',sendMessage);$('#messageInput').addEventListener('input',e=>autosize(e.target));$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});$('#demoBtn').addEventListener('click',loadDemo);$$('[data-demo="1"]').forEach(b=>b.addEventListener('click',loadDemo));$('#newCaseBtn').addEventListener('click',openModal);$('#newCaseRailBtn').addEventListener('click',openModal);$$('[data-open="new"]').forEach(b=>b.addEventListener('click',openModal));$('#closeModal').addEventListener('click',closeModal);$('#cancelModal').addEventListener('click',closeModal);$('#caseModal').addEventListener('click',e=>{if(e.target.id==='caseModal')closeModal()});$('#caseForm').addEventListener('submit',createCase);$('#refreshCases').addEventListener('click',loadCases);$('#markNormalBtn').addEventListener('click',()=>submitFeedback(0));$('#markMarketingBtn').addEventListener('click',()=>submitFeedback(1));$$('.insight-tabs button').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$('#attachBtn').addEventListener('click',()=>$('#assetInput').click());$('#assetInput').addEventListener('change',e=>{uploadToCurrent([...e.target.files]);e.target.value=''});$('#modalAttachBtn').addEventListener('click',()=>$('#modalAssetInput').click());$('#modalAssetInput').addEventListener('change',e=>{addPendingFiles(e.target.files);e.target.value=''});
let dragDepth=0;document.addEventListener('dragenter',e=>{if([...e.dataTransfer?.types||[]].includes('Files')){dragDepth++;$('#dropLayer').hidden=false}});document.addEventListener('dragleave',()=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('#dropLayer').hidden=true});document.addEventListener('dragover',e=>{if([...e.dataTransfer?.types||[]].includes('Files'))e.preventDefault()});document.addEventListener('drop',e=>{if(e.dataTransfer?.files?.length){e.preventDefault();dragDepth=0;$('#dropLayer').hidden=true;uploadToCurrent([...e.dataTransfer.files])}});
loadCases();
